<a href="https://colab.research.google.com/github/eroombob/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np1 = np.random.rand(3,4)
np1


array([[0.05562967, 0.35904255, 0.16910803, 0.39714874],
       [0.86204144, 0.26228011, 0.52563794, 0.0845054 ],
       [0.02882778, 0.61207626, 0.13782792, 0.698751  ]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(4, 3, 2)
tensor_3d

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.0556, 0.3590, 0.1691, 0.3971],
        [0.8620, 0.2623, 0.5256, 0.0845],
        [0.0288, 0.6121, 0.1378, 0.6988]], dtype=torch.float64)