<a href="https://colab.research.google.com/github/eroombob/Pytorch-Tutorial-Youtube/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# addition shorthand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# addition longhand, use a function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# subtraction

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# mutliplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# mul function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# div function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# modulus function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# another way to add
torch.add(tensor_a, 10)

tensor([21, 24, 27, 30])

In [ ]:
# reassignment (weird)
#tensor_a = torch.tensor([1,2,3,4])
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])